language: node_js
node_js:
- '5.0'
before_script:
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal $BROWSERSTACK_KEY localhost,9090 > &
- sleep 5
- npm run server &
env:
  matrix:
  - BROWSER: Firefox
    PLATFORM: Win8
    VERSION: 41
  - BROWSER: Chrome
    PLATFORM: Win8
    VERSION: 46
  - BROWSER: Safari
    PLATFORM: Mac
    VERSION: 9
  global:
  - secure: KyHuj2zzEPfNQ3CgaMXv8t3fpxvp+AWFfKcvYHDDH4DnJwj9oVK/XLzPsGbCUIJuyXXMrqbkvp7TpNuGJcAuo2yI0e58yG5Y8sbh7oHUGTjfI7grKypRt7e+MWakNOLETxmv6bH2oSTegZRlLvsoXWyYoigHtJw3u8n+tWAXTFXxCBVzgHphTha5fJBJ5fCDRkvPOf/mZzRJ1LneJiYOyy2vRu+SC/hFImJcfCzVb8iwKcU1oPCHlnXbYEwlTHBA61eUJLqRMNIwdOUW4jDYO8G8ycPqla9DDNoL0sdPhvkSXFDFi5Eo46uQMHa0L62DPLTxezVlf6gafJWVc7PWf7L7TeLe6GO7d2vKjLzcU+0ZKxTypRRrUJFrY0Zr2CsJWRy71MBaj4yoPsqDGVPKuIZS9j0MVCsPWYidq05WmY6wEAZYLCWF31qqwv+fHwtc3pKjaDKTy72s/swEjyLRkG5hXGnF+XpePBB7fOkYZr+yzISCDFCUoVmI96CniV4wRoqnPnHHPBBPoL0YULFdsPF2cbM628Ur+h8kO5sgpn7HtAalJHqzxiay6kzess5jw+FqnR3386QzmejjO7c6OhUH8nvOGmkDuQKNfd5Z74kDTg1c4bSHu//UA0jv1MSOWPnGl58nmbDU8Em2O2ZqdKUFB02YrOcRnErYbfMhJLs=
  - secure: Xr2QU/zQmA+on4TdN2Fbi+xwLgZxPGk8Kv8XzsaT6NDYMFcqEilgL0xfu/SUxRhdGH7WcemsnXuMUI6uMkvczLfZ7UkmC9i/8j3fNRMzvEjN3khqlATEjZjoQS+xsx0mLMoBDrO+GOxs3dnF5Lzg0Y9injLHK44ZpPlgPprMOBcxAOPIBN8nCHVLtFb6TqSQi/HLZH5hTLb5AucPKLkmeCwkOsFhr3DoLmI6HH5wzQOL3wkrIeneOAzcvof8pDxIzF1VXWwqjaa9Fva1WYKf1YBeG8ipDGUf3CTFXlGFusW3IFUUGwVdvWCT4/hnG3sXmGxafH1Mt4RmkeVZ8jXqZc44VCU+F01qXr7PAr/FbvAUVX8d7RHd+VPgkMdku4pMdlToNnmblaZ8mUyBfgSSEWkoQ5i0PldbnS91cdTpWVDAJlyEUuYKr5sLsaXJIEHscyQOxg1r3GRRRlyYBCsBZjbESDkCKas3AWo8sRtIIcqE2frZXgRz+V9Uuq2OWi6Cz32FdveV6pNkj/MEpbBlSopIPonEtEc0gmHfDSM1FIgUwtJO7ASNt2BtzapkmjM9hAdVw2vMGUnSx9JEWGC5AbyyogG9Aqglx1as7jGdNrNuZfIg+IKHb+/mQBY6YcZUnGtcUYeroEKYCdTLYJscR74mFH/8q+Rqha1lIL1Dvbs=
